name: Android Emulator tests
on: pull_request
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=\"-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false\" -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dkotlin.daemon.jvm.options=-Xmx8G,-XX:MaxMetaspaceSize=512m,-Dorg.gradle.daemon=false,-Dkotlin.incremental=false"
  JAVA_OPTS: "-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 120

jobs:
  build:
    uses: ./.github/workflows/setup_macos.yaml
    with:
      gradleTask: bundleLibRuntimeToJarDebug

  test:
    needs: build
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        api-level: [23, 33]
        module: ${{ fromJSON(needs.build.outputs.projects) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup tools and cache for workspace
        uses: ./.github/workflows/setup_tools_macos/
        with:
          kotlinVersion: ${{ needs.build.outputs.kotlinVersion }}

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd.v5-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          disk-size: 3G
          ram-size: 3G
          heap-size: 1500M
          profile: 3.4in WQVGA
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          disk-size: 3G
          ram-size: 3G
          heap-size: 1500M
          profile: 3.4in WQVGA
          script: ./gradlew :${{ matrix.module }}:connectedDebugAndroidTest
