name: Android Emulator tests
on: [pull_request, push]
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=\"-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false\" -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dkotlin.daemon.jvm.options=-Xmx8G,-XX:MaxMetaspaceSize=512m,-Dorg.gradle.daemon=false,-Dkotlin.incremental=false"
  JAVA_OPTS: "-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-12
    outputs:
      projects: ${{ steps.envFile.outputs.projects }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # remove VM settings as defined for using the IDE
      - run: sed -i '' -e '/org.gradle.jvmargs/d' gradle.properties; cat gradle.properties

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution : 'temurin'
          java-version : 11

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-includes: |
            caches
            notifications
            configuration-cache

      - name: Konan cache
        uses: actions/cache@v3
        id: konan-cache
        with:
          path: ~/.konan/*
          key: konan

      - run: ./gradlew generateNonDependentProjectsFile

      - name: load projects for build matrix
        uses: cardinalby/export-env-action@v2
        id: envFile
        with:
          envFile: 'non_dependent_projects.properties'
          export: 'false'

      - name: Make cache of workspace
        uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ./*
            !/.gradle
          key: build-emulator-${{ github.sha }}

      - run: ./gradlew bundleLibRuntimeToJarDebug

  test:
    needs: build
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        api-level: [23, 32]
        module: ${{ fromJSON(needs.build.outputs.projects) }}
    steps:
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            configuration-cache

      - name: Get cache of workspace
        uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ./*
            !/.gradle
          key: build-emulator-${{ github.sha }}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd.v3-${{ matrix.api-level }}

      - name: Konan cache
        uses: actions/cache@v3
        id: konan-cache
        with:
          path: ~/.konan/*
          key: konan

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          disk-size: 3G
          ram-size: 3G
          heap-size: 1500M
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          disk-size: 3G
          ram-size: 3G
          heap-size: 1500M
          script: ./gradlew :${{ matrix.module }}:connectedDebugAndroidTest