#### for keeping up to date with settings.gradle.kts see instructions in `test:` job, then
#### also update the `--dry-run connectedDebugAndroidTest` run with the same module name

name: Android Emulator tests
on: push
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx8g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # remove VM settings as defined for using the IDE
      - run: sed -i '' -e '/org.gradle.jvmargs/d' gradle.properties

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution : 'temurin'
          java-version : 11

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-includes: |
            caches
            notifications
            configuration-cache

      - name: Make cache of workspace
        uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ./*
            !/.gradle
          key: build-${{ github.sha }}

      - run: ./gradlew --no-daemon --configuration-cache --parallel bundleLibRuntimeToJarDebug
      # fill the configuration cache for the matrix test, not required but will speed up builds
      - run: ./gradlew --no-daemon --configuration-cache --parallel --dry-run connectedDebugAndroidTest :base:connectedDebugAndroidTest :beacons:connectedDebugAndroidTest :bluetooth:connectedDebugAndroidTest :architecture:connectedDebugAndroidTest :alerts:connectedDebugAndroidTest :date-time:connectedDebugAndroidTest :logging:connectedDebugAndroidTest :hud:connectedDebugAndroidTest :permissions:connectedDebugAndroidTest :location:connectedDebugAndroidTest :keyboard:connectedDebugAndroidTest :links:connectedDebugAndroidTest :resources:connectedDebugAndroidTest :review:connectedDebugAndroidTest :scientific:connectedDebugAndroidTest :system:connectedDebugAndroidTest :test-utils:connectedDebugAndroidTest
  
  test:
    needs: build
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        api-level: [23, 32]
        # some custom gradle magic makes tests run grouped for `$module-*` and `*-$module` on CI so there is no need to add these to the matrix
        module: [
          "base",
          "beacons",
          "bluetooth",
          "architecture",
          "alerts",
          "date-time",
          "logging",
          "hud",
          "permissions",
          "location",
          "keyboard",
          "links",
          "resources",
          "review",
          "scientific",
          "system",
          "test-utils"
        ]
    steps:
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            configuration-cache

      - name: Get cache of workspace
        uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ./*
            !/.gradle
          key: build-${{ github.sha }}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Konan cache
        uses: actions/cache@v3
        id: konan-cache
        with:
          path: ~/.konan/*
          key: konan

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          force-avd-creation: false
          emulator-options:  -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -cores 3
          disable-animations: true
          arch: x86_64
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -cores 3
          disable-animations: true
          arch: x86_64
          script: ./gradlew --no-daemon --configuration-cache --parallel :${{ matrix.module }}:connectedDebugAndroidTest