name: iOS tests
on: [pull_request, push]
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=\"-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false\" -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dkotlin.daemon.jvm.options=-Xmx8G,-XX:MaxMetaspaceSize=512m,-Dorg.gradle.daemon=false,-Dkotlin.incremental=false"
  JAVA_OPTS: "-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    uses: ./.github/workflows/setup_macos.yaml
    with:
      gradleTask: compileKotlinIosX64

  test:
    needs: build
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.build.outputs.projects) }}
    steps:
      - name: restore workspace
        uses: ./.github/workflows/restore_workspace_macos.yaml
        with:
          kotlinVersion: needs.build.outputs.kotlinVersion

      - name: run tests
        run: ./gradlew :${{ matrix.module }}:iosX64Test